#ifndef ASSIGNMENT1_ROBOT_STATUS_H
#define ASSIGNMENT1_ROBOT_STATUS_H

enum ROBOT_STATUS {
    REQUEST_CANCELED,
    GOAL_UNREACHABLE,
    GOAL_RECEIVED,
    INSIDE_NARROW,
    OUTSIDE_NARROW,
    ROBOT_MOVING,
    ROBOT_REACHED,
    ROBOT_SCANNING,
    ROBOT_COMPLETED_DETECTION,
    ROBOT_MOVING_NARROW
};

const char* statusToString(ROBOT_STATUS status);

#endif // ASSIGNMENT1_ROBOT_STATUS_H
