#ifndef ASSIGNMENT1_ROBOT_STATUS_H
#define ASSIGNMENT1_ROBOT_STATUS_H

enum ROBOT_STATUS {
    GOAL_RECEIVED,
    GENERATING_WAYPOINTS,
    MOVING,
    SCANNING,
    SCAN_COMPLETE,
    MOVE_FAILED,
    NAVIGATION_COMPLETED,
    GOAL_REACHED,
    GOAL_FAILED,
    TAG_FOUND,
    TILT_HEAD
};

const char* statusToString(ROBOT_STATUS status);

#endif // ASSIGNMENT1_ROBOT_STATUS_H
